-
  name: 'test GraphQL API'
  uriPattern: 'api-test/test-endpoint'
  defaults:
    '@package':    'Oniva.GraphQL'
    '@controller': 'GraphQL'
    '@action':     'query'
    '@format':     'json'
    'endpoint':    'test-endpoint'
  httpMethods: [POST]
