-
  name: 'graphql - endpoint'
  uriPattern: '<endpoint>'
  defaults:
    '@package':    'Oniva.GraphQL'
    '@controller': 'GraphQL'
    '@action':     'query'
    '@format':     'json'
    'endpoint':    '<endpoint>'
  httpMethods: [POST]
