Neos:
  Flow:
    http:
      middlewares:
        'graphQLOptions':
          position: 'before routing'
          middleware: 'Oniva\GraphQL\Http\HttpOptionsMiddleware'
    log:
      graphQLRequestLogger:
        logger: Neos\Flow\Log\Logger
        backend: Neos\Flow\Log\Backend\FileBackend
        backendOptions:
          logFileURL: '%FLOW_PATH_DATA%Logs/GraphQLRequests.log'
          createParentDirectories: true
          severityThreshold: '%LOG_INFO%'
          maximumLogFileSize: 10485760
          logFilesToKeep: 1
          logMessageOrigin: false

Oniva:
  GraphQL:
    context: 'Oniva\GraphQL\Context'
    includeExceptionMessageInOutput: true
    endpoints: []
#      'some-endpoint':
#        'logRequests': true  # if enabled all requests are logged
#        'context:' 'Foo\Vendor\GraphQL\Context  # optional context that overrides the global context
#        'schemaEnvelope': 'Some\Fully\Qualified\Namespace'
#        'errorTransform': Oniva\GraphQL\Transform\FlowErrorTransform # optional: override the default error transformer for this schema
